Repository PdxCodeGuild/class_olive, pull requests merged in 2022-08, with the labels that each got.

#18 Finished version 1... I think
  code/tim/python/lab03.py
Labels: Review In Progress

#21 lab_03
  code/lauren/python/lab_03.py
Labels: Review Complete

#22 version 1 and 2
  code/rebeca/python/lab02b.py
Labels: Review Complete

#25 Lab2B Robert
  code/robert/python/lab2b.py
Labels: Review Complete

#27 Kevin s python lab03 optional1
  code/Kevin/Python/lab03.py
  code/Kevin/Python/lab03op1.py
Labels: Review Complete

#29 Committing lab4
  code/nathan/python/lab4.py
Labels: Review In Progress

#30 lauren_o-python-lab09
  code/lauren/python/lab-09.py
  code/lauren/python/lab_2a.py
Labels: Review In Progress

#31 Blackjack_Robert
  code/robert/python/blackjack.py
Labels: Review Complete

#32 blackjack lab
  code/rebeca/python/lab09.py
Labels: Review Complete

#33 Kevins python blackjack lab
  code/Kevin/Python/lab04.py
Labels: Review In Progress

#36 pick6_robert
  code/robert/python/pick6.py
Labels: Review In Progress, Review Complete

#38 Pick6
  code/robert/python/pick6_original.py
  code/robert/python/pick6_retry.py
Labels: Review Complete

#40 Kevin's Python Lab05 "Pick6"
  code/Kevin/Python/lab05.py
Labels: Review In Progress

#41 Tim b python lab08
  code/tim/python/lab08.py
Labels: Review Complete

#37 committing pick6 lab
  code/nathan/python/lab5.py
Labels: Review In Progress

#43 Lauren o python creditcard
  code/lauren/python/creditcard.py
  code/lauren/python/pick6.py
  code/lauren/python/rot13.py
Labels: Review Complete

#23 Kevin s python lab03
  code/Kevin/Python/lab03.py
Labels: Change Requested

#47 CCV_Robert
  code/robert/python/creditcard validation.py
Labels: Review Complete

#52 Tim b python mob jackalope
  code/tim/python/mob_jackalope.py
Labels: Review Complete

#53 Kevin's python group_jackalopes
  code/Kevin/Python/grouplab01.py
  code/Kevin/Python/lab07.py
Labels: Review Complete

#56 Committing Rot Cipher lab
  code/nathan/python/rot_cipher.py
Labels: Review Complete

#60 Kant ARI
  code/robert/python/ARI.py
  code/robert/python/kant.txt
Labels: Review In Progress

#63 Committing ARI Lab
  code/nathan/python/ARI_Lab.py
  code/nathan/python/The_Sun_Also_Rises.txt
Labels: Review Complete

#70 Create rot13.py
  code/robert/python/rot13.py
  rot13.py
Labels: Review In Progress

#76 Nathan committing bio html/css lab
  code/nathan/html_css/bio_lab/Teddy.jpg
  code/nathan/html_css/bio_lab/background.jpg
  code/nathan/html_css/bio_lab/bio.html
  code/nathan/html_css/bio_lab/bio_style.css
Labels: Review In Progress

#71 Tim b python lab11 contacts
  code/tim/python/lab11_contacts.py
  code/tim/python/lab11_input.csv
  code/tim/python/lab11_output.csv
Labels: Review In Progress

#74 Kevin's python lab "CRUD"
  code/Kevin/Python/contacts_crud.csv
  code/Kevin/Python/lab_crud.py
  code/Kevin/Python/output_test.csv
Labels: Review In Progress

#72 committing contact_list lab
  code/nathan/python/contact_list.csv
  code/nathan/python/contact_list.py
Labels: Review Complete

#78 contactlist
  code/lauren/python/contactlist.py
  code/lauren/python/contacts.csv
Labels: Review Complete

#79 Tim b python lab12 atm
  code/tim/python/lab12_atm.py
Labels: Review In Progress

#80 ATM Robert
  code/robert/python/ATM.py
Labels: Review In Progress

#81 Kevin's Python ATM Lab
  code/Kevin/Python/atm_lab.py
Labels: Review In Progress
