Repository PdxCodeGuild/class_olive, pull requests merged in 2022-09, with the labels that each got.

#85 Nathan committing dad jokes lab
  code/nathan/python/dad_jokes.py
Labels: Review In Progress

#88 Kevin's - python - "Dad joke lab"
  code/Kevin/Python/ac-dc_calc.py
  code/Kevin/Python/dadlab.py
Labels: Review In Progress

#90 Nathan committing quotes api lab
  code/nathan/python/quotes_api.py
Labels: Review Complete

#91 Kevin's Python "Quotes API" lab
  code/Kevin/Python/quotes_api.py
Labels: Review Complete

#92 Robert Quotes
  code/robert/python/quotes.py
Labels: Review Complete

#94 Dadjokes robert
  code/robert/python/papajokes.py
Labels: Review In Progress

#82 Nathan committing blog html/css lab
  code/nathan/html_css/blog_lab/about_me.html
  code/nathan/html_css/blog_lab/contact.html
  code/nathan/html_css/blog_lab/cow.png
  code/nathan/html_css/blog_lab/elk.png
  code/nathan/html_css/blog_lab/home.png
  code/nathan/html_css/blog_lab/index.html
  code/nathan/html_css/blog_lab/person.png
  code/nathan/html_css/blog_lab/phone.png
  code/nathan/html_css/blog_lab/pronghorn.png
  code/nathan/html_css/blog_lab/styles.css
  code/nathan/html_css/blog_lab/tarpon.png
  code/nathan/html_css/company_lab/index.html
  code/nathan/html_css/company_lab/logo.png
  code/nathan/html_css/company_lab/styles.css
Labels: Change Requested

#96 lauren_o-quotesapi
  code/lauren/python/quotesapi.py
Labels: Review In Progress

#97 Tim b python lab15 quotes
  code/tim/python/lab15-quotes.py
Labels: Review In Progress

#100 Kevin's python Mini-capstone.
  code/Kevin/Python/.gitignore
  code/Kevin/Python/Calculations.py
  code/Kevin/Python/discord_bot_test.py
  code/Kevin/Python/pick6.py
  code/Kevin/Python/resis_color_calc.py
Labels: Review Complete

#101 Tim b python mini capstone
  code/tim/python/mini_capstone/.gitignore
  code/tim/python/mini_capstone/gamebot_v1.py
  code/tim/python/mini_capstone/gamebot_v2.py
  code/tim/python/mini_capstone/midweather.py
Labels: Review Complete

#102 Nathan h national parks
  code/nathan/python/this_land_is_your_land_see_it/.gitignore
  code/nathan/python/this_land_is_your_land_see_it/national_parks.py
  code/nathan/python/this_land_is_your_land_see_it/nps_parks_api.py
  code/nathan/python/this_land_is_your_land_see_it/save.txt
  code/nathan/python/this_land_is_your_land_see_it/states.txt
Labels: Review Complete

#103 News robert
  code/robert/python/capstone/capstone/.gitignore
  code/robert/python/capstone/capstone/adfontes2019.csv
  code/robert/python/capstone/capstone/allsides.csv
  code/robert/python/capstone/capstone/allsides.json
  code/robert/python/capstone/capstone/config.py
  code/robert/python/capstone/capstone/newsbias.py
Labels: Review Complete

#105 lauren_o-minicapstone
  code/lauren/python/.emv
  code/lauren/python/minicapstone.py
Labels: Review Complete

#107 Tim b python lab19 dad jokes
  code/tim/python/lab19-dad_jokes.py
Labels: Review Complete

#108 Lauren o bio
  code/lauren/python/.gitignore
  code/lauren/python/bio.css
  code/lauren/python/bio.html
  code/lauren/python/minicapstone.py
Labels: Review Complete

#109 Robert Gudetama
  code/robert/css/GloriaHallelujah-Regular.ttf
  code/robert/css/Gudetama_Fall.jpg
  code/robert/css/OFL.txt
  code/robert/css/biolab.html
  code/robert/css/gudetama egg shell.png
  code/robert/css/gudetama on repeat.jpg
  code/robert/css/gudetama2.jpg
  code/robert/css/gudetama_train.jpeg
  code/robert/css/gudetama_vox.0.jpg
  code/robert/css/sanrio background.jpeg
  code/robert/css/styles.css
Labels: Review Complete

#114 Kevin's HTML lab2 "Company Home" abomination
  code/Kevin/HTML/lab2/crap/Manolio's.png
  code/Kevin/HTML/lab2/crap/construction_type_guy.gif
  code/Kevin/HTML/lab2/crap/internetparty.gif
  code/Kevin/HTML/lab2/crap/undercongid.gif
  code/Kevin/HTML/lab2/crap/underconstructionspin.gif
  code/Kevin/HTML/lab2/index.html
  code/Kevin/HTML/lab2/styles.css
  code/Kevin/HTML/lab2/styles_d.css
Labels: Change Requested

#116 Tim b html css lab02 company
  code/tim/HTML+CSS/lab02_company/index.html
  code/tim/HTML+CSS/lab02_company/static/desktop_styles.css
  code/tim/HTML+CSS/lab02_company/static/styles.css
Labels: Review In Progress

#106 finished but ugly
  code/tim/HTML+CSS/lab01_Bio/index.html
  code/tim/HTML+CSS/lab01_Bio/styles.css
Labels: Change Requested

#115 Committing flask blog lab nathan
  code/nathan/flask/hello.py
  code/nathan/flask/static/bigger_desktop_styles.css
  code/nathan/flask/static/cow.png
  code/nathan/flask/static/desktop_styles.css
  code/nathan/flask/static/elk.png
  code/nathan/flask/static/home.png
  code/nathan/flask/static/person.png
  code/nathan/flask/static/phone.png
  code/nathan/flask/static/pronghorn.png
  code/nathan/flask/static/styles.css
  code/nathan/flask/static/warpon.png
  code/nathan/flask/templates/about.html
  code/nathan/flask/templates/contact.html
  code/nathan/flask/templates/index.html
Labels: Review Complete

#119 Muki html lab3 blog
  code/muki/HTML/lab3-blog/app.py
  code/muki/HTML/lab3-blog/static/images/Galaxy-Cupcakes.jpg
  code/muki/HTML/lab3-blog/static/style.css
  code/muki/HTML/lab3-blog/templates/lab3blog.html
Labels: Review Complete

#113 Astroblocks robert
  code/robert/css/Company Page/about us.html
  code/robert/css/Company Page/analyticslink.html
  code/robert/css/Company Page/astroblocks background.jpg
  code/robert/css/Company Page/astroblocks.html
  code/robert/css/Company Page/consult.html
  code/robert/css/Company Page/desktop_styles.css
  code/robert/css/Company Page/rocket.gif
  code/robert/css/Company Page/styles.css
  code/robert/css/Company Page/visualizationslink.html
Labels: Review Complete
