Repository PdxCodeGuild/class_olive, pull requests merged in 2022-11, with the labels that each got.

#160 Kevin's JavaScript lab2 "Hacker Lab"
  code/Kevin/JavaScript/lab2/index.html
  code/Kevin/JavaScript/lab2/script.js
  code/Kevin/JavaScript/lab2/strongbad.png
  code/Kevin/JavaScript/lab2/styles.css
Labels: Review Complete

#163 Tim b javascript mob lab
  code/tim/javascript/mob_lab/index.html
  code/tim/javascript/mob_lab/script.js
  code/tim/javascript/mob_lab/styles.css
Labels: Review Complete

#165 Kevin's Javascript lab3 "Group lab: Kevin, Robert, Lauren."
  code/Kevin/JavaScript/lab3/index.html
  code/Kevin/JavaScript/lab3/script.js
Labels: Review Complete

#66 Ari lab
  code/Grant/python/ARI/ari.py
  code/Grant/python/ARI/book.txt
  code/Grant/python/ARI/book_2.txt
  code/Grant/python/ARI/book_3.txt
Labels: Ready For Review

#164 Kevin's Javascript Lab4 "Quotes lab"
  code/Kevin/JavaScript/lab4/index.html
  code/Kevin/JavaScript/lab4/script.js
Labels: Review Complete

#167 committing quotes api lab
  code/nathan/javascript/quotes_api/quotes.html
  code/nathan/javascript/quotes_api/quotes.js
  code/nathan/javascript/quotes_api/styles.css
Labels: Review Complete

#170 vue todo complete
  code/nathan/javascript/.gitignore
  code/nathan/javascript/vue_todo/styles.css
  code/nathan/javascript/vue_todo/todo.html
  code/nathan/javascript/vue_todo/todo.js
Labels: Review Complete

#177 Nathan quiz game
  code/nathan/javascript/quiz_game/quiz.html
  code/nathan/javascript/quiz_game/quiz.js
  code/nathan/javascript/quiz_game/styles.css
Labels: Review Complete

#178 robertCSSBlog
  code/robert/css/blog/GloriaHallelujah-Regular.ttf
  code/robert/css/blog/aboutUs.html
  code/robert/css/blog/home.html
  code/robert/css/blog/joinUs.html
  code/robert/css/blog/styles.css
  code/robert/css/blog/yeti background.jpg
Labels: Review In Progress

#144 it's not pretty but it gets the job done. like me.
  code/tim/Django/lab02_url_shortener/url_shorten_project/manage.py
  code/tim/Django/lab02_url_shortener/url_shorten_project/url_app/__init__.py
  code/tim/Django/lab02_url_shortener/url_shorten_project/url_app/admin.py
  code/tim/Django/lab02_url_shortener/url_shorten_project/url_app/apps.py
  code/tim/Django/lab02_url_shortener/url_shorten_project/url_app/migrations/0001_initial.py
  code/tim/Django/lab02_url_shortener/url_shorten_project/url_app/migrations/0002_rename_long_url_urlmodel_myfield.py
  code/tim/Django/lab02_url_shortener/url_shorten_project/url_app/migrations/0003_rename_myfield_urlmodel_url_field.py
  code/tim/Django/lab02_url_shortener/url_shorten_project/url_app/migrations/0004_rename_url_field_urlmodel_long_url_field.py
  code/tim/Django/lab02_url_shortener/url_shorten_project/url_app/migrations/0005_urlmodel_short_url_code.py
  code/tim/Django/lab02_url_shortener/url_shorten_project/url_app/migrations/0006_urlmodel_url_name_alter_urlmodel_long_url_field.py
  code/tim/Django/lab02_url_shortener/url_shorten_project/url_app/migrations/0007_alter_urlmodel_long_url_field_and_more.py
  code/tim/Django/lab02_url_shortener/url_shorten_project/url_app/migrations/0008_alter_urlmodel_long_url_field_and_more.py
  code/tim/Django/lab02_url_shortener/url_shorten_project/url_app/migrations/0009_remove_urlmodel_url_name.py
  code/tim/Django/lab02_url_shortener/url_shorten_project/url_app/migrations/0010_urlmodel_url_name.py
  code/tim/Django/lab02_url_shortener/url_shorten_project/url_app/migrations/0011_alter_urlmodel_url_name.py
  code/tim/Django/lab02_url_shortener/url_shorten_project/url_app/migrations/0012_alter_urlmodel_long_url_field_and_more.py
  code/tim/Django/lab02_url_shortener/url_shorten_project/url_app/migrations/__init__.py
  code/tim/Django/lab02_url_shortener/url_shorten_project/url_app/models.py
  code/tim/Django/lab02_url_shortener/url_shorten_project/url_app/static/favicon.ico
  code/tim/Django/lab02_url_shortener/url_shorten_project/url_app/static/url_app/styles.css
  code/tim/Django/lab02_url_shortener/url_shorten_project/url_app/templates/url_app/home.html
  code/tim/Django/lab02_url_shortener/url_shorten_project/url_app/templates/url_app/navbar.html
  code/tim/Django/lab02_url_shortener/url_shorten_project/url_app/tests.py
  code/tim/Django/lab02_url_shortener/url_shorten_project/url_app/urls.py
  code/tim/Django/lab02_url_shortener/url_shorten_project/url_app/views.py
  code/tim/Django/lab02_url_shortener/url_shorten_project/url_shorten_project/__init__.py
  code/tim/Django/lab02_url_shortener/url_shorten_project/url_shorten_project/asgi.py
  code/tim/Django/lab02_url_shortener/url_shorten_project/url_shorten_project/settings.py
  code/tim/Django/lab02_url_shortener/url_shorten_project/url_shorten_project/urls.py
  code/tim/Django/lab02_url_shortener/url_shorten_project/url_shorten_project/wsgi.py
Labels: Change Requested

#179 Tim b javascript lab05 quiz game
  code/tim/javascript/lab05_quiz_game/correct.png
  code/tim/javascript/lab05_quiz_game/incorrect.png
  code/tim/javascript/lab05_quiz_game/index.html
  code/tim/javascript/lab05_quiz_game/script.js
  code/tim/javascript/lab05_quiz_game/styles.css
  code/tim/javascript/lab05_quiz_game/wasted.png
  code/tim/javascript/lab05_quiz_game/winner.png
Labels: Review In Progress

#180 lauren-jvascript-quiz
  code/lauren/django/grocerylist/Pipfile
  code/lauren/django/quickstart_lab/Pipfile
  code/lauren/flask/company/companyhome.html
  code/lauren/flask/company/static/desktop_styles.css
  code/lauren/flask/company/static/styles.css
  code/lauren/flask/static/desktop_styles.css
  code/lauren/flask/static/style.css
  code/lauren/flask/templates/index.html
  code/lauren/javascript/vuequizgame/index.html
  code/lauren/javascript/vuequizgame/javascript.code-workspace
  code/lauren/javascript/vuequizgame/script.js
  code/lauren/javascript/vuequizgame/styles.css
Labels: Review In Progress

#181 Tim b django lab04 blog
  code/tim/Django/lab04_blog/blog_project/blog_project/__init__.py
  code/tim/Django/lab04_blog/blog_project/blog_project/asgi.py
  code/tim/Django/lab04_blog/blog_project/blog_project/settings.py
  code/tim/Django/lab04_blog/blog_project/blog_project/urls.py
  code/tim/Django/lab04_blog/blog_project/blog_project/wsgi.py
  code/tim/Django/lab04_blog/blog_project/manage.py
  code/tim/Django/lab04_blog/blog_project/posts/__init__.py
  code/tim/Django/lab04_blog/blog_project/posts/admin.py
  code/tim/Django/lab04_blog/blog_project/posts/apps.py
  code/tim/Django/lab04_blog/blog_project/posts/migrations/0001_initial.py
  code/tim/Django/lab04_blog/blog_project/posts/migrations/0002_rename_user_blog_post_author.py
  code/tim/Django/lab04_blog/blog_project/posts/migrations/0003_blog_post_public.py
  code/tim/Django/lab04_blog/blog_project/posts/migrations/0004_alter_blog_post_public.py
  code/tim/Django/lab04_blog/blog_project/posts/migrations/__init__.py
  code/tim/Django/lab04_blog/blog_project/posts/models.py
  code/tim/Django/lab04_blog/blog_project/posts/tests.py
  code/tim/Django/lab04_blog/blog_project/posts/urls.py
  code/tim/Django/lab04_blog/blog_project/posts/views.py
  code/tim/Django/lab04_blog/blog_project/static/css/styles.css
  code/tim/Django/lab04_blog/blog_project/static/favicon.png
  code/tim/Django/lab04_blog/blog_project/templates/base.html
  code/tim/Django/lab04_blog/blog_project/templates/home.html
  code/tim/Django/lab04_blog/blog_project/templates/post_delete.html
  code/tim/Django/lab04_blog/blog_project/templates/post_detail.html
  code/tim/Django/lab04_blog/blog_project/templates/post_edit.html
  code/tim/Django/lab04_blog/blog_project/templates/post_new.html
  code/tim/Django/lab04_blog/blog_project/templates/profile.html
  code/tim/Django/lab04_blog/blog_project/templates/register.html
  code/tim/Django/lab04_blog/blog_project/templates/registration/login.html
  code/tim/Django/lab04_blog/blog_project/users/__init__.py
  code/tim/Django/lab04_blog/blog_project/users/admin.py
  code/tim/Django/lab04_blog/blog_project/users/apps.py
  code/tim/Django/lab04_blog/blog_project/users/migrations/__init__.py
  code/tim/Django/lab04_blog/blog_project/users/models.py
  code/tim/Django/lab04_blog/blog_project/users/tests.py
  code/tim/Django/lab04_blog/blog_project/users/urls.py
  code/tim/Django/lab04_blog/blog_project/users/views.py
Labels: Review In Progress
